export const SET_TOKEN_USER = 'SET_TOKEN_USER';
export const IS_LOADING = 'IS_LOADING'
export const STACK_IS_LOADING = 'STACK_IS_LOADING'
export const SIGNIN_IS_ERROR = 'SIGNIN_IS_ERROR'
export const SIGNUP_IS_ERROR = 'SIGNUP_IS_ERROR'
export const SIGNUP_IS_SUCCESS = 'SIGNUP_IS_SUCCESS'